[shell]
program='/usr/bin/zsh'
[window]
opacity = 0.92
[window.padding]
x = 5
y = 10
[font]
size = 13
[font.normal]
family='FantasqueSansMNerdFont'
style='Regular'
[font.bold]
family='FantasqueSansMNerdFont'
style='Bold'
[font.italic]
family='FantasqueSansMNerdFont'
style='Italic'

